---
- name: check if nested virtualization is enabled
  block:
    - command: cat /sys/module/kvm_intel/parameters/nested
      register: nested_virt_enabled
      changed_when: false
  rescue:
    - command: cat /sys/module/kvm_amd/parameters/nested
      register: nested_virt_enabled
      changed_when: false

- name: enable nested virtualization in kvm config
  modprobe:
    name: kvm_intel
    state: present
    params: "nested=1"
  when: nested_virt_enabled.stdout == "N"
