- name: 'Install dependencies'
  win_shell: Install-windowsfeature -name AD-Domain-Services –IncludeManagementTools

- name: 'Create new AD domain sub.ad.vm'
  win_shell: |
    Import-Module ADDSDeployment
    $user = "Administrator@ad.vm"
    $password = ConvertTo-SecureString -String "vagrant" -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential($user,$password)

    Install-ADDSDomain                                                        \
      -Credential $credential                                                 \
      -NewDomainName "sub"                                                    \
      -ParentDomainName "ad.vm"                                               \
      -NewDomainNetbiosName "ADCHILD"                                         \
      -Force:$true                                                            \
      -InstallDns:$true                                                       \
      -NoRebootOnCompletion:$true                                             \
      -SafeModeAdministratorPassword                                          \
        (ConvertTo-SecureString 'Secret123' -AsPlainText -Force)
  args:
    creates: 'C:\Windows\NTDS'
