---
- hosts: all
  gather_facts: no
  vars:
    - ansible_winrm_server_cert_validation: ignore
    - ansible_winrm_operation_timeout_sec: 60
    - ansible_winrm_read_timeout_sec: 70
  roles:
    - win-ping
